# Generated by Django 4.0.6 on 2022-07-14 05:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('WalletAddress', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlantName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tagyourtree.user')),
            ],
        ),
        migrations.CreateModel(
            name='PlantDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='Files/')),
                ('lati', models.DecimalField(decimal_places=6, max_digits=9)),
                ('long', models.DecimalField(decimal_places=6, max_digits=9)),
                ('date', models.DateField()),
                ('plantname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tagyourtree.plantname')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tagyourtree.user')),
            ],
        ),
    ]
