# Generated by Django 4.0.6 on 2022-07-15 09:08

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('WalletAddress', models.CharField(blank=True, max_length=255, null=True)),
                ('plantName', models.CharField(blank=True, max_length=200, null=True)),
                ('is_plant_name_is_active', models.BooleanField(default=True)),
                ('week1', models.BooleanField(default=False)),
                ('week2', models.BooleanField(default=True)),
                ('week3', models.BooleanField(default=True)),
                ('week4', models.BooleanField(default=True)),
                ('weekPercentage', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ImageMetaData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='images', verbose_name='File')),
                ('weekno', models.CharField(blank=True, max_length=10, null=True)),
                ('lati', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('long', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('metadata_date', models.DateField(blank=True, null=True)),
                ('present_date', models.DateField(default=datetime.date.today)),
                ('ipfs_hash', models.CharField(blank=True, max_length=200, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tagyourtree.user')),
            ],
        ),
    ]
