# Generated by Django 4.0.6 on 2022-07-15 06:04

import datetime
from django.db import migrations, models
import django.db.models.deletion
import tagyourtree.models


class Migration(migrations.Migration):

    dependencies = [
        ('tagyourtree', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageMetaData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to=tagyourtree.models.get_file_path, verbose_name='File')),
                ('weekno', models.CharField(blank=True, max_length=10, null=True)),
                ('lati', models.DecimalField(decimal_places=6, max_digits=9)),
                ('long', models.DecimalField(decimal_places=6, max_digits=9)),
                ('metadata_date', models.DateField()),
                ('present_date', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.RemoveField(
            model_name='plantname',
            name='user',
        ),
        migrations.AddField(
            model_name='user',
            name='is_plant_name_is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='plantName',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='week1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='week2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='week3',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='week4',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='PlantDetails',
        ),
        migrations.DeleteModel(
            name='PlantName',
        ),
        migrations.AddField(
            model_name='imagemetadata',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tagyourtree.user'),
        ),
    ]
