# Generated by Django 4.0.6 on 2022-07-15 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tagyourtree', '0002_imagemetadata_remove_plantname_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='week2',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='week3',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='week4',
            field=models.BooleanField(default=True),
        ),
    ]
