# Generated by Django 4.0.6 on 2022-07-15 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tagyourtree', '0003_alter_user_week2_alter_user_week3_alter_user_week4'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='weekPercentage',
            field=models.IntegerField(default=0),
        ),
    ]
